-- Task C3

CREATE TABLE orku_stodvar_eigandi(    --stod er að ná í þetta
    ID              SERIAL PRIMARY KEY,
    heiti_eigandans VARCHAR UNIQUE,--eigandi í orku_einingar
);     --þetta er þjónustufyrirtækiðCREATE VIEW monthly_plant_loss_ratio AS

CREATE TABLE hnit (
    ID          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    X_HNIT      DOUBLE PRECISION,
    Y_HNIT      DOUBLE PRECISION
);

CREATE TABLE orku(
    ID                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stadur              VARCHAR NOT NULL UNIQUE,
    dagsetning_uppsett  DATE NOT NULL,
    hnit_id             INT NOT NULL,
    stodvar_id          INT NOT NULL,
    FOREIGN KEY(hnit_id) REFERENCES hnit(ID),
    FOREIGN KEY(stodvar_id) REFERENCES orku_stodvar_eigandi(ID)
);

CREATE TABLE virkjun(
    ID          INT PRIMARY KEY REFERENCES orku(ID),
    tegund      VARCHAR NOT NULL
);

CREATE TABLE stod ( 
    ID          INT PRIMARY KEY REFERENCES orku(ID),
    tegund      VARCHAR NOT NULL
);

CREATE TABLE tengdar_stodvar (
    STOD1        VARCHAR,
    STOD2        VARCHAR,
    PRIMARY KEY(STOD1, STOD2),
    FOREIGN KEY(STOD1) REFERENCES orku(stadur),
    FOREIGN KEY(STOD2) REFERENCES orku(stadur)
);

CREATE TABLE notandi (
    ID          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hnit_id     INT,    --KEY
    stadsetning VARCHAR NOT NULL,   --heiti
    kennitala   VARCHAR NOT NULL UNIQUE,
    eigandi     VARCHAR NOT NULL,
    ar_stofnad  VARCHAR NOT NULL,   --ar_stofnað í notendur_skranning
    FOREIGN KEY(hnit_id) REFERENCES hnit(ID)
);    --þetta er fyrirtæki sem er að nota þjónustuna


CREATE TABLE maeling(
    ID                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orku_ID             INT,    -- sendandi_maelingar 
    sendandi_orku_id    INT,
    sendandi_eigandi_id INT,
    tegund_maelingar    VARCHAR NOT NULL,
    FOREIGN KEY (orku_ID) REFERENCES orku(ID),
    FOREIGN KEY (sendandi_orku_id) REFERENCES orku(ID),
    FOREIGN KEY (sendandi_eigandi_id) REFERENCES orku_stodvar_eigandi(ID),
    sendandi VARCHAR GENERATED ALWAYS AS (
        (CASE WHEN sendandi_orku_id IS NOT NULL THEN 's' || sendandi_orku_id
        WHEN sendandi_eigandi_id IS NOT NULL THEN 'e' || sendandi_eigandi_id END)) STORED,
    UNIQUE (orku_ID, sendandi, tegund_maelingar)

    CONSTRAINT exclusive_sender CHECK (
        (sendandi_orku_id IS NOT 0 AND sendandi_eigandi_id IS 0) OR
        (sendandi_orku_id IS 0 AND sendandi_eigandi_id IS NOT 0))
);

CREATE TABLE gildin(
    ID              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maeling_ID      INT,
    notandi_ID      INT NULL,
    gildi_kwh       NUMERIC NOT NULL,
    timi            TIMESTAMP NOT NULL,
    FOREIGN KEY (notandi_ID) REFERENCES notandi(ID)
    FOREIGN KEY (maeling_ID) REFERENCES maeling(ID)
);


CREATE TRIGGER check_if_makes_sense
ON new_improved



SELECT *
FROM orku_stodvar_eigandi
LIMIT 10;

SELECT *
FROM gildin
LIMIT 1000;

SELECT *
FROM maeling
LIMIT 1000;

SELECT *
FROM notandi
LIMIT 100;

SELECT *
FROM tengdar_stodvar
LIMIT 100;

SELECT *
FROM orku
LIMIT 100;

SELECT *
FROM hnit
LIMIT 100;



-- Task D1

--Q1

CREATE INDEX index_maeling_orku
on maeling(orku_ID, tegund_maelingar);

--Q2
CREATE INDEX index_gildin_timi_maeling_notandi
on gildin((EXTRACT(YEAR FROM timi)), maeling_ID, notandi_ID);

--Q3
CREATE INDEX index_gildin_maeling
on gildin(maeling_ID);