-- Task C3

CREATE TABLE orku_stodvar_eigandi(    --stod er að ná í þetta
    ID              SERIAL PRIMARY KEY,
    heiti_eigandans VARCHAR UNIQUE,--eigandi í orku_einingar
);     --þetta er þjónustufyrirtækið

--CREATE VIEW monthly_plant_loss_ratio AS ...

CREATE TABLE hnit (
    ID          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    X_HNIT      DOUBLE PRECISION,
    Y_HNIT      DOUBLE PRECISION
);

CREATE TABLE orku(
    ID                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stadur              VARCHAR NOT NULL UNIQUE,
    dagsetning_uppsett  DATE NOT NULL,
    hnit_id             INT NOT NULL,
    stodvar_id          INT NOT NULL,
    FOREIGN KEY(hnit_id) REFERENCES hnit(ID),
    FOREIGN KEY(stodvar_id) REFERENCES orku_stodvar_eigandi(ID)
);

CREATE TABLE virkjun(
    ID          INT PRIMARY KEY REFERENCES orku(ID),
    tegund      VARCHAR NOT NULL
);

CREATE TABLE stod ( 
    ID          INT PRIMARY KEY REFERENCES orku(ID),
    tegund      VARCHAR NOT NULL
);

CREATE TABLE tengdar_stodvar (
    STOD1        VARCHAR,
    STOD2        VARCHAR,
    PRIMARY KEY(STOD1, STOD2),
    FOREIGN KEY(STOD1) REFERENCES orku(stadur),
    FOREIGN KEY(STOD2) REFERENCES orku(stadur)
);

CREATE TABLE notandi (
    ID          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hnit_id     INT,    --KEY
    stadsetning VARCHAR NOT NULL,   --heiti
    kennitala   VARCHAR NOT NULL UNIQUE,
    eigandi     VARCHAR NOT NULL,
    ar_stofnad  VARCHAR NOT NULL,   --ar_stofnað í notendur_skranning
    FOREIGN KEY(hnit_id) REFERENCES hnit(ID)
);    --þetta er fyrirtæki sem er að nota þjónustuna


CREATE TABLE maeling(
    ID                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orku_ID             INT,    -- sendandi_maelingar 
    sendandi_orku_id    INT,
    sendandi_eigandi_id INT,
    tegund_maelingar    VARCHAR NOT NULL,
    FOREIGN KEY (orku_ID) REFERENCES orku(ID),
    FOREIGN KEY (sendandi_orku_id) REFERENCES orku(ID),
    FOREIGN KEY (sendandi_eigandi_id) REFERENCES orku_stodvar_eigandi(ID),
    sendandi VARCHAR GENERATED ALWAYS AS (
        CASE 
            WHEN sendandi_orku_id IS NOT NULL THEN 's' || sendandi_orku_id
            WHEN sendandi_eigandi_id IS NOT NULL THEN 'e' || sendandi_eigandi_id 
        END 
    )STORED,
    UNIQUE (orku_ID, sendandi, tegund_maelingar),

    CONSTRAINT exclusive_sender CHECK (
        (sendandi_orku_id IS NOT NULL AND sendandi_eigandi_id IS NULL) OR
        (sendandi_orku_id IS NULL AND sendandi_eigandi_id IS NOT NULL))
);

CREATE TABLE gildin(
    ID              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maeling_ID      INT,
    notandi_ID      INT NULL,
    gildi_kwh       NUMERIC NOT NULL,
    timi            TIMESTAMP NOT NULL,
    FOREIGN KEY (notandi_ID) REFERENCES notandi(ID),
    FOREIGN KEY (maeling_ID) REFERENCES maeling(ID)
);

-- Task D1
DROP TRIGGER IF EXISTS CheckEnergyFlow ON gildin;
DROP FUNCTION IF EXISTS CheckEnergyFlow();


CREATE FUNCTION CheckEnergyFlow()
RETURNS TRIGGER
AS
$$
DECLARE
	tOrkuID INT;
	tTimi TIMESTAMP;

	tFramleidsla NUMERIC;
	tInnmotun NUMERIC;
	tUttekt NUMERIC;

	oldOrkuID INT;
	oldTimi TIMESTAMP;
BEGIN
	IF (TG_OP = 'INSERT') THEN
		SELECT M.orku_ID
		INTO tOrkuID
		FROM maeling M
		WHERE M.ID = NEW.maeling_ID;

		tTimi := NEW.timi;

	ELSIF (TG_OP = 'DELETE') THEN
		SELECT M.orku_ID
		INTO tOrkuID
		FROM maeling M
		WHERE M.ID = OLD.maeling_ID;

		tTimi := OLD.timi;

	ELSIF (TG_OP = 'UPDATE') THEN
		SELECT M.orku_ID
		INTO tOrkuID
		FROM maeling M
		WHERE M.ID = NEW.maeling_ID;

		tTimi := NEW.timi;

		IF (OLD.maeling_ID <> NEW.maeling_ID OR OLD.timi <> NEW.timi) THEN
			SELECT M.orku_ID
			INTO oldOrkuID
			FROM maeling M
			WHERE M.ID = OLD.maeling_ID;

			oldTimi := OLD.timi;

			SELECT
				COALESCE(SUM(CASE WHEN M.tegund_maelingar = 'Framleiðsla' THEN G.gildi_kwh ELSE 0 END), 0),
				COALESCE(SUM(CASE WHEN M.tegund_maelingar = 'Innmötun' THEN G.gildi_kwh ELSE 0 END), 0),
				COALESCE(SUM(CASE WHEN M.tegund_maelingar = 'Úttekt' THEN G.gildi_kwh ELSE 0 END), 0)
			INTO tFramleidsla, tInnmotun, tUttekt
			FROM gildin G
			     JOIN maeling M ON M.ID = G.maeling_ID
			WHERE M.orku_ID = oldOrkuID
			  AND G.timi = oldTimi;

			IF (tFramleidsla <= tInnmotun) THEN
				RAISE EXCEPTION 'Function CheckEnergyFlow: Framleiðsla must be greater than Innmötun!' USING ERRCODE = '45000';
			END IF;

			IF (tInnmotun <= tUttekt) THEN
				RAISE EXCEPTION 'Function CheckEnergyFlow: Innmötun must be greater than total Úttekt!' USING ERRCODE = '45000';
			END IF;
		END IF;
	END IF;

	SELECT
		COALESCE(SUM(CASE WHEN M.tegund_maelingar = 'Framleiðsla' THEN G.gildi_kwh ELSE 0 END), 0),
		COALESCE(SUM(CASE WHEN M.tegund_maelingar = 'Innmötun' THEN G.gildi_kwh ELSE 0 END), 0),
		COALESCE(SUM(CASE WHEN M.tegund_maelingar = 'Úttekt' THEN G.gildi_kwh ELSE 0 END), 0)
	INTO tFramleidsla, tInnmotun, tUttekt
	FROM gildin G
	     JOIN maeling M ON M.ID = G.maeling_ID
	WHERE M.orku_ID = tOrkuID
	  AND G.timi = tTimi;

	IF (tFramleidsla <= tInnmotun) THEN
		RAISE EXCEPTION 'Function CheckEnergyFlow: Framleiðsla must be greater than Innmötun!' USING ERRCODE = '45000';
	END IF;

	IF (tInnmotun <= tUttekt) THEN
		RAISE EXCEPTION 'Function CheckEnergyFlow: Innmötun must be greater than Úttekt!' USING ERRCODE = '45000';
	END IF;

	IF (TG_OP = 'DELETE') THEN
		RETURN OLD;
	END IF;

	RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER CheckEnergyFlow
AFTER INSERT OR UPDATE OR DELETE
ON gildin
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE PROCEDURE CheckEnergyFlow();
